version: "3"

volumes:
  postgresql_data:
    driver: local

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobz
    ports:
      - 5433:5432
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@localhost
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
    ports:
      - 8000:8000
    # restart: always
    volumes:
      - ./src:/home/guest/jobz/src
