# Generated by Django 3.2.9 on 2021-12-02 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'área de atuação',
                'verbose_name_plural': 'áreas de atuação',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=50, verbose_name='RG')),
                ('orgao_expedidor', models.CharField(max_length=50, verbose_name='órgão expedidor')),
                ('data_expedicao', models.DateField(verbose_name='data de expedição')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descrição')),
                ('especificacoes', models.TextField(verbose_name='especificações')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=11)),
                ('fax', models.CharField(blank=True, max_length=11, null=True)),
                ('newsletter_subscriber', models.BooleanField(default=False, verbose_name='inscrever na newsletter')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('area_atuacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areaatuacao', verbose_name='área de atuação')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contato', verbose_name='contato')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'estados civis',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='FormaContratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'forma de contratação',
                'verbose_name_plural': 'formas de contratação',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'gênero',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descrição')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'unidade federativa',
                'verbose_name_plural': 'unidades federativas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='remuneração')),
                ('vale_transporte', models.BooleanField(default=False, verbose_name='vale transporte')),
                ('vale_refeicao', models.BooleanField(default=False, verbose_name='vale refeição')),
                ('outros', models.TextField()),
                ('localidade', models.CharField(max_length=200)),
                ('candidatos', models.ManyToManyField(blank=True, to='core.Candidato')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('forma_contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formacontratacao', verbose_name='forma de contratação')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uf', verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefas_executadas', models.TextField(verbose_name='tarefas executadas')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('forma_contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formacontratacao', verbose_name='forma de contratação')),
            ],
            options={
                'verbose_name': 'experiência profissinal',
                'verbose_name_plural': 'experiências profissionais',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('tipo_logradouro', models.CharField(max_length=50, verbose_name='tipo de logradouro')),
                ('bairroDistrito', models.CharField(max_length=200, verbose_name='bairro ou distrito')),
                ('localidade', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uf', verbose_name='UF')),
            ],
            options={
                'verbose_name': 'endereço',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contato', verbose_name='contato'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadocivil'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='uf_expedicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uf', verbose_name='UF de expedição'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
